FROM vitess/bootstrap:percona57

# Re-copy sources from working tree
USER root
COPY . /vt/src/vitess.io/vitess

# Download vendored Go dependencies
RUN cd /vt/src/vitess.io/vitess && \
    go get -u github.com/kardianos/govendor && \
    govendor sync && \
    rm -rf /vt/.cache

# Build Vitess
RUN make build

# Fix permissions
RUN chown -R vitess:vitess /vt
USER vitess

